#!/usr/bin/env python
import sys
import os
from pyroma import packagedata, ratings

argument = sys.argv[1]

# Is the argument a path?

if os.path.isdir(argument):
    print('========')
    print('Checking')
    print('========')
    data = packagedata.get_data(os.path.abspath(argument))
    rating = ratings.rate(data)

elif os.path.isfile(argument):
    # A zipe or tgz or egg file or something like that
    print("Sorry, the distributon checking isn't implemented yet.")
    sys.exit(1)
    
else:
    # Its probably a package name
    print("Sorry, the PyPI checking isn't implemented yet.")
    sys.exit(1)
    
for problem in rating[1]:
    # XXX It would be nice with a * pointlist instead, but that requires
    # that we know how wide the terminal is and nice word-breaks, so that's
    # for later.
    print(problem)
print('========')
print('Final rating: ' + str(rating[0]) + '/10')
print(ratings.LEVELS[rating[0]])
print('========')
