#!/usr/bin/env python
import sys
import os
from pyroma import projectdata, distributiondata, ratings

argument = sys.argv[1]

# Is the argument a path?

print('========')
print('Checking ' + argument)
print('========')

if os.path.isdir(argument):
    data = projectdata.get_data(os.path.abspath(argument))
    rating = ratings.rate(data)

elif os.path.isfile(argument):
    data = distributiondata.get_data(os.path.abspath(argument))
    rating = ratings.rate(data)
    
else:
    # Its probably a package name
    print("Sorry, the PyPI checking isn't implemented yet.")
    sys.exit(1)
    
for problem in rating[1]:
    # XXX It would be nice with a * pointlist instead, but that requires
    # that we know how wide the terminal is and nice word-breaks, so that's
    # for later.
    print(problem)
if rating[1]:
    print('========')
print('Final rating: ' + str(rating[0]) + '/10')
print(ratings.LEVELS[rating[0]])
print('========')
